AllCops:
  Include:
    - '**/Rakefile'
    - Gemfile
    - tachikoma.gemspec
    - bin/**/*
    - lib/**/*.rake
  Exclude:
    - pkg/**/*
    - repos/**/*
    - vendor/**/*
StringLiterals:
  EnforcedStyle: single_quotes
LineLength:
  Max: 120
Blocks:
  Enabled: false
Style/DotPosition:
  Enabled: true
